services:
  - type: web
    name: spatial
    env: static
    # No build step needed for a single HTML file
    buildCommand: ""
    # Publish directory expected by Render service config
    staticPublishPath: frontend
    pullRequestPreviewsEnabled: true

